(function() {var implementors = {};
implementors["async_dnssd"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"async_dnssd/struct.BrowsedFlags.html\" title=\"struct async_dnssd::BrowsedFlags\">BrowsedFlags</a>",synthetic:false,types:["async_dnssd::service::browse::BrowsedFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"async_dnssd/struct.RegisterRecordFlags.html\" title=\"struct async_dnssd::RegisterRecordFlags\">RegisterRecordFlags</a>",synthetic:false,types:["async_dnssd::service::connection::RegisterRecordFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"async_dnssd/struct.EnumeratedFlags.html\" title=\"struct async_dnssd::EnumeratedFlags\">EnumeratedFlags</a>",synthetic:false,types:["async_dnssd::service::enumerate_domains::EnumeratedFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"async_dnssd/struct.QueryRecordFlags.html\" title=\"struct async_dnssd::QueryRecordFlags\">QueryRecordFlags</a>",synthetic:false,types:["async_dnssd::service::query_record::QueryRecordFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"async_dnssd/struct.QueriedRecordFlags.html\" title=\"struct async_dnssd::QueriedRecordFlags\">QueriedRecordFlags</a>",synthetic:false,types:["async_dnssd::service::query_record::QueriedRecordFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"async_dnssd/struct.RegisterFlags.html\" title=\"struct async_dnssd::RegisterFlags\">RegisterFlags</a>",synthetic:false,types:["async_dnssd::service::register::RegisterFlags"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
