var N = null;var sourcesIndex = {};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["encoding_rs"] = {"name":"","files":["ascii.rs","big5.rs","data.rs","euc_jp.rs","euc_kr.rs","gb18030.rs","handles.rs","iso_2022_jp.rs","lib.rs","macros.rs","mem.rs","replacement.rs","shift_jis.rs","single_byte.rs","utf_16.rs","utf_8.rs","variant.rs","x_user_defined.rs"]};
sourcesIndex["memchr"] = {"name":"","dirs":[{"name":"x86","files":["avx.rs","mod.rs","sse2.rs"]}],"files":["fallback.rs","iter.rs","lib.rs","naive.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["fallback.rs","lib.rs","strnom.rs","wrapper.rs"]};
sourcesIndex["quick_xml"] = {"name":"","dirs":[{"name":"events","files":["attributes.rs","mod.rs"]}],"files":["errors.rs","escape.rs","lib.rs","reader.rs","utils.rs","writer.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["gen_helper.rs"]}],"files":["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["xml_data"] = {"name":"","dirs":[{"name":"parser","files":["core.rs","default.rs","extensions.rs","fixed_element.rs","ignore.rs","inner.rs","mod.rs","value.rs"]},{"name":"quick_xml","files":["mod.rs","parser.rs","serializer.rs"]},{"name":"serializer","files":["core.rs","fixed_element.rs","inner.rs","mod.rs","value.rs"]}],"files":["errors.rs","extensions.rs","lib.rs","traits.rs"]};
sourcesIndex["xml_data_derive"] = {"name":"","files":["attributes.rs","element.rs","lib.rs","parser.rs","serialize.rs"]};
createSourceSidebar();
